version: "2"
services:
  web:
    container_name: web
    restart: always
    build: .
    ports:
      - "5000:5000"
    links:
      - mongo
    depends_on:
      - "mongo"
  mongo:
    container_name: mongo
    image: mongo
    command: mongod --port 27018
    volumes:
      - ./data:/data/db
    ports:
      - "27018:27018"
